# packages in environment at /Users/williamrobinson/miniconda3/envs/northnet-env:
#
# Name                    Version                   Build  Channel
appnope                   0.1.2           py39hecd8cb5_1001  
backcall                  0.2.0                      py_0    anaconda
beautifulsoup4            4.9.3              pyha847dfd_0  
boost                     1.74.0           py39ha641261_3    conda-forge
boost-cpp                 1.74.0               h43a636a_2    conda-forge
brotlipy                  0.7.0           py39h9ed2024_1003  
bzip2                     1.0.8                h0d85af4_4    conda-forge
ca-certificates           2021.4.13            hecd8cb5_1  
cairo                     1.16.0            he43a7df_1008    conda-forge
certifi                   2020.12.5        py39hecd8cb5_0  
cffi                      1.14.5           py39h2125817_0  
chardet                   4.0.0           py39hecd8cb5_1003  
conda                     4.10.1           py39hecd8cb5_1  
conda-build               3.21.4           py39hecd8cb5_0  
conda-package-handling    1.7.3            py39h9ed2024_1  
cryptography              3.4.7            py39h2fd3fbb_0  
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    anaconda
filelock                  3.0.12             pyhd3eb1b0_1  
fontconfig                2.13.1            h10f422b_1005    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
glob2                     0.7                pyhd3eb1b0_0  
greenlet                  1.0.0            py39h9fcab8e_0    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      2.10               pyhd3eb1b0_0  
ipykernel                 5.3.4            py39h01d92e1_0  
ipython                   7.22.0           py39h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jedi                      0.17.2           py39hecd8cb5_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jupyter_client            5.3.3                      py_0    anaconda
jupyter_core              4.5.0                      py_0    anaconda
kiwisolver                1.3.1            py39hedf5dff_1    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
libarchive                3.4.2                haa3ed63_0  
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_22    conda-forge
libgfortran5              9.3.0               h6c81a4c_22    conda-forge
libglib                   2.68.1               hd556434_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
liblief                   0.10.1               h23ab428_1  
libopenblas               0.3.15          openmp_h5e1b9a4_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libsodium                 1.0.18               h1de35cc_0    anaconda
libtiff                   4.2.0                h7c11950_1    conda-forge
libwebp-base              1.2.0                h0d85af4_2    conda-forge
libxml2                   2.9.10               h93ec3fd_4    conda-forge
llvm-openmp               11.1.0               hda6cdc1_1    conda-forge
llvmlite                  0.36.0                   pypi_0    pypi
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markupsafe                1.1.1            py39h9ed2024_0  
matplotlib-base           3.4.1            py39hb07454d_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
networkx                  2.5.1                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.20.2           py39h7eed0ac_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1k               h9ed2024_0  
pandas                    1.2.4            py39h23ab428_0  
parso                     0.7.0                      py_0    anaconda
pcre                      8.44                 hb1e8313_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.1.2            py39h5fdd921_1    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
pkginfo                   1.7.0            py39hecd8cb5_0  
prompt-toolkit            3.0.8                      py_0    anaconda
psutil                    5.8.0            py39h9ed2024_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py-lief                   0.10.1           py39h23ab428_1  
pycairo                   1.20.0           py39hbe14034_1    conda-forge
pycosat                   0.6.3            py39h9ed2024_0  
pycparser                 2.20                       py_2  
pygments                  2.7.1                      py_0    anaconda
pygraphviz                1.7                      pypi_0    pypi
pynndescent               0.5.2                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py39hecd8cb5_0  
python                    3.9.2           h2502468_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-graphviz           0.16                     pypi_0    pypi
python-libarchive-c       2.9                pyhd3eb1b0_1  
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39h9ed2024_1  
pyzmq                     20.0.0           py39h23ab428_1  
rdkit                     2021.03.1        py39h88273a1_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
reportlab                 3.5.67           py39hf37cc50_0    conda-forge
requests                  2.25.1             pyhd3eb1b0_0  
ripgrep                   12.1.1                        0  
ruamel_yaml               0.15.100         py39h9ed2024_0  
scikit-learn              0.24.2           py39h4b1dcc9_0    conda-forge
scipy                     1.6.3            py39h056f1c0_0    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.2.1              pyhd3eb1b0_0  
sqlalchemy                1.4.13           py39h89e85a6_0    conda-forge
sqlite                    3.35.5               h44b9ce1_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tornado                   6.1              py39hcbf5805_1    conda-forge
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5                      py_0    anaconda
tzdata                    2021a                he74cb21_0    conda-forge
umap-learn                0.5.1                    pypi_0    pypi
urllib3                   1.26.4             pyhd3eb1b0_0  
wcwidth                   0.2.5                      py_0    anaconda
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0  
zeromq                    4.3.3                hb1e8313_3    anaconda
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge
